---
- name: Create directory
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy compressed backend folder
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend
    owner: ubuntu

# - name: Run the web server
#   become: true
#   shell:
#     cmd: |
#       cd /home/ubuntu/backend
#       npm install
#       pm2 stop default
#       pm2 delete default
#       pm2 start npm -- start
- name: start app
  become: true
  shell: |
    cd backend
    pm2 delete all
    pm2 start npm -- start
      