
---
- name: Create directory
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy compressed backend folder
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend
    owner: ubuntu

- name: Run the web server
  become: true
  shell: |
    cd ~/backend
    npm install --force
    pm2 stop default
    pm2 start npm -- start
  register: command_output

- name: Display command output 
  debug:  
     var: command_output.stdout_lines