---

- name: 'update and upgrade packages.'
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: remove unneeded deps
  become: true
  apt:
    autoremove: yes

- name: install deps
  become: true
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes
    
- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: Create directory
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy compressed backend folder
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend
    owner: ubuntu

# - name: Run the web server
#   become: true
#   shell:
#     cmd: |
#       cd /home/ubuntu/backend
#       npm install
#       pm2 stop default
#       pm2 delete default
#       pm2 start npm -- start
- name: start app
  become: true
  shell: |
    cd /home/ubuntu/backend
    ls
    pm2 delete all
    pm2 start npm -- start
      